#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-XOXO
version:      0.032
version_from: lib/XML/XOXO.pm
installdirs:  site
requires:
    Class::XPath:                  1.4
    XML::Parser:                   2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
