#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-XOXO
version:      0.03
version_from: lib/XML/XOXO/Parser.pm
installdirs:  site
requires:
    XML::Parser:                   2
    Class::XPath:                  1.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
